POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbXVlbEBnbWFpbC5jb20iLCJleHAiOjE3NjMyMzExMTAsInVzZXJJZCI6MX0.ldKYv2Qy0odwL_tC6-dGVCPEfJVd7WtLswlgN1mYAbs

{
    "name": "Movement Day",
    "description": "Moving from Ibadan to ilesha",
    "location": "Ilesha",
    "dateTime": "2023-10-01T10:00:00Z"
}