POST http://localhost:8080/events
Content-Type: application/json

{
    "name": "Test event",
    "description": "This is a test event",
    "location": "Test location",
    "dateTime": "2023-10-01T10:00:00Z"
}