DELETE http://localhost:8080/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbXVlbDFAZ21haWwuY29tIiwiZXhwIjoxNzY2NDMyNjUwLCJ1c2VySWQiOjJ9.A6r_pWUNvB0RLIRS8qJ4qWoi4DRvpY9BA0Y9Olg4Etw