POST http://localhost:8080/events/1/register
Content-Type: "application/json"
Authorization: eyJhbGciOiJIUzI1NiIsnR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbXVlbDFAZ21haWwuY29tIiwiZXhwIjoxNzYzMjMxMzE3LCJ1c2VySWQiOjJ9.QLxoS0FfJ3yY93xExer5BqO42ewZy3wsXGEup3c_hWg